language: go
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
install:
  - go get -t ./...
services:
  - redis-server
after_success:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
go:
  - 1.6.4
  - 1.7.5
  - 1.8
  - 1.9.2
